name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: registry.misw.jp
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: |
            registry.misw.jp/portal-role-sync/portal-role-sync
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push images
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "."
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
